"""Modified is_deleted for all

Revision ID: 3a7912ea6bae
Revises: 85b32c0d49ed
Create Date: 2024-12-18 15:34:58.653993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7912ea6bae'
down_revision: Union[str, None] = '85b32c0d49ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_documents', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_documents', sa.Column('deleted_at', sa.DateTime(), server_default='2033-12-31 22:59:59+07', nullable=False))
    op.add_column('user_pictures', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_pictures', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_pictures', sa.Column('deleted_at', sa.DateTime(), server_default='2033-12-31 22:59:59+07', nullable=False))
    op.add_column('user_serials', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_serials', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_serials', sa.Column('deleted_at', sa.DateTime(), server_default='2033-12-31 22:59:59+07', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_serials', 'deleted_at')
    op.drop_column('user_serials', 'created_at')
    op.drop_column('user_serials', 'is_deleted')
    op.drop_column('user_pictures', 'deleted_at')
    op.drop_column('user_pictures', 'created_at')
    op.drop_column('user_pictures', 'is_deleted')
    op.drop_column('user_documents', 'deleted_at')
    op.drop_column('user_documents', 'created_at')
    op.drop_column('user_documents', 'is_deleted')
    # ### end Alembic commands ###
