"""Pictures and Serials

Revision ID: 5cd652125341
Revises: 40f5c42bb083
Create Date: 2024-12-15 19:47:25.774997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cd652125341'
down_revision: Union[str, None] = '40f5c42bb083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('Обычная', 'Важная', name='picturesgenres'), nullable=False),
    sa.Column('picture', postgresql.BYTEA(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_serials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('genre', postgresql.ENUM('Комедия', 'Ужасы', 'Драма', 'Фантастика', 'Фэнтези', 'Приключения', 'Сит ком', name='serialsgenres'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_serials')
    op.drop_table('user_pictures')
    # ### end Alembic commands ###
