"""Modified table films

Revision ID: 85b32c0d49ed
Revises: 5cd652125341
Create Date: 2024-12-18 13:38:03.568046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b32c0d49ed'
down_revision: Union[str, None] = '5cd652125341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_films', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_films', sa.Column('deleted_at', sa.DateTime(), server_default='2033-12-31 22:59:59+07', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_films', 'deleted_at')
    op.drop_column('user_films', 'created_at')
    # ### end Alembic commands ###
